homepage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from homepage import views

app_name = "homepage"
urlpatterns = [
    path("developers/", views.dev_list, name="devlist"),
    path("developers/<slug:slug>", views.dev_view, name="dev"),
    path("game_news/", views.gamenews, name="gamenews"),
    path("", views.dev_view, name="dev"),
    path("developer_news/", views.devgamesfunct, name="devall"),
    path("my_favorites/", views.dev_user, name="devuser"),
    path("about/", views.about, name="about"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from sitemaps import *

sitemaps = {
    'static': StaticViewSitemap,
    'dev_model': DevSitemap
}

urlpatterns = [
    path("", include("homepage.urls")),
    path("", include("users.urls")),
    path("", include('django.contrib.auth.urls')),
    path('admin/clearcache/', include('clearcache.urls')),
    path("admin/", admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views as user_views

app_name = "users"

urlpatterns = [
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path("password_reset", user_views.password_reset_request, name="password_reset"),
]



templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content=""/>
    <meta
            name="author"
            content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Hugo 0.79.0"/>

    <title>
        Gamer News Depot{% block title %}{% endblock title %}
    </title>

    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
            crossorigin="anonymous"
    />

    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>

    {% block header %}
    {% endblock header %}

    <style>

      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }


      .nav_text {
        font-weight: bold;
        color:black;
      }

      {% block style %}
      {% endblock style %}
    {% block header_style %}
    {% endblock header_style %}

    </style>

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-1023Z1GZNV"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-1023Z1GZNV');
    </script>
    <script data-ad-client="ca-pub-9538862532414339" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
    <script>
    {% block header_script %}
    {% endblock header_script%}
    </script>
</head>
<body class="bg-light">

<nav class="navbar navbar-expand-md2 navbar-light bg-light fixed-top">

    <div class="container-fluid">
        <a href="{% url 'homepage:dev' %}">
        <img width="255px" class="navbar-brand" src="{% static 'logo_default.svg' %}">
        </a>

        <div class="btn-group" style="float:right" style="left:40px;">
            <button
                    class="navbar-toggler"
                    type="button"
                    id="dropdownMenuButton"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if user.is_authenticated %}
            <div class="dropdown-menu dropdown-menu-right" style="margin-left:-95px;min-width:0;text-align:right;"
                 aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'homepage:gameews' %}">Game News</a>
                <a class="dropdown-item" href="{% url 'homepage:devall' %}">Developer News</a>
                <a class="dropdown-item" href="{% url 'homepage:devlist' %}">Developers</a>
                <a class="dropdown-item" href="{% url 'homepage:devuser' %}">Favorites</a>
                <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                <a class="dropdown-item" href="{% url 'homepage:about' %}">About</a>

            </div>
            {% else %}
            <div class="dropdown-menu dropdown-menu-right" style="margin-left:-95px;min-width:0;text-align:right;"
                 aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'homepage:gameews' %}">Game News</a>
                <a class="dropdown-item" href="{% url 'homepage:devall' %}">Developer News</a>
                <a class="dropdown-item" href="{% url 'homepage:devlist' %}">Developers</a>
                <a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'users:register' %}">Register</a>
                <a class="dropdown-item" href="{% url 'homepage:about' %}">About</a>
            </div>
            {% endif %}
        </div>
        <div class="collapse navbar-collapse  font-weight-bold nav_text" id="navbarsExampleDefault" style="white-space: nowrap;">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage:gameews' %}">Game News</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage:devall' %}">Developer News</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="{% url 'homepage:devlist' %}">Developers</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:devuser' %}">Favorites</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a
                            class="nav-link dropdown-toggle"
                            href="#"
                            id="dropdown01"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false">Account</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'homepage:about' %}">About</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" href="{% url 'homepage:about' %}">About</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div style="margin-top: 7rem;">

{% block content%}
{% endblock content %}

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>{% block javascript %}{% endblock javascript %}</script>

</body>
</html>